# Exported from Render on 2025-10-25T16:42:16Z
version: "1"
projects:
- name: My project
  environments:
  - name: Production
    services:
    - type: web
      name: citizen-safety
      runtime: python
      repo: https://github.com/ki-money/citizen-safety
      plan: free
      region: oregon
      buildCommand: pip install -r requirements.txt
      startCommand: gunicorn app:app
      autoDeployTrigger: commit
